version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - postgres-env.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3050:80"

  api:
    stdin_open: true
    container_name: api
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - db

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      dockerfile: Dockerfile.dev
      context: "./frontend"
    volumes:
      - /app/node_modules
      - ./frontend:/app
