version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password

  nginx: 
    depends_on:
      - api
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: "./nginx"
    ports: 
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  # frontend: 
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: "./frontend"
  #   volumes:
  #     - /app/node_modules
  #     - ./frontend:/app